apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-ui-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-ui-dashboard
  template:
    metadata:
      labels:
        app: ts-ui-dashboard
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/iron-bedrock-366809/train-ticket/ts-ui-dashboard:0.2.1
        imagePullPolicy: Always
        name: ts-ui-dashboard
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ts-ui-dashboard
spec:
  ports:
  - name: http
    nodePort: 32677
    port: 8080
  selector:
    app: ts-ui-dashboard
  type: NodePort
